version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=shopper
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - db     
    ports:
      - "8000:8000"
  redis:
    image: redis
  worker:
    image: shopper_django
    command: celery -A Shopper worker -l info
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=Shopper.settings
      - C_FORCE_ROOT=true
    depends_on:
      - django    
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - el_data://usr/share/elasticsearch/data
    ports:
      - 9200:9200
    labels:
      - co.elastic.logs/module=elasticsearch
      - co.elastic.metrics/module=elasticsearch
    
volumes:
  pg_data:
    driver: local  
  el_data:
    driver: local