FROM python:3-slim
RUN apt-get update && apt-get install -y libpq-dev gcc
ENV PYTHONBUFFERED 1
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code
RUN pip install -r requirements.txt
COPY . /code/