# Generated by Django 3.1.7 on 2021-03-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0002_tag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.IntegerField(choices=[(1, 'litres'), (2, 'milliliters'), (3, 'grams'), (4, 'pieces')], default=1),
            preserve_default=False,
        ),
    ]
