# Generated by Django 3.1.7 on 2021-03-31 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0002_remove_ingredient_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='group',
        ),
        migrations.RemoveField(
            model_name='product',
            name='group',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='group',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='group',
        ),
    ]
