# Generated by Django 3.1.7 on 2021-03-08 18:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0007_remove_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Recipes.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='last_used',
            field=models.DateTimeField(null=True),
        ),
    ]
